### ISSUE TITLE
Replace `listr`

### ISSUE THREAD

**Issue by TangRufus** [ItinerisLtd/composify#22]
Because of:
- https://github.com/SamVerschueren/listr/issues/120
- https://github.com/SamVerschueren/listr/issues/121
- https://github.com/SamVerschueren/listr/issues/32
- https://github.com/sindresorhus/np/issues/131

**Comment by guyisra** [comment]
what are the alternatives?

**Comment by TangRufus** [comment]
For this project, I found listr is an overkill. Using these satisfies my needs:

- https://github.com/oclif/cli-ux
- https://oclif.io/docs/commands#command-methods
- https://www.npmjs.com/package/chalk
